config/routes.rb
Rorschach::Application.routes.draw do


  get 'info', to: 'static#info'
  get 'user/:name', to: 'users#show'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'auth/failure', to: redirect('/')
  match 'drawings', to: 'drawings#all', as: 'drawings'
  match 'kitteh', to: 'kitteh#index', as: 'kitteh'


  resources :users, :only => [:index, :show, :update]

  # resources :prompts, :except => [:edit, :update] do
  resources :inkblots, :except => [:edit, :update], :controller => 'prompts', :as => 'prompts' do
    resources :drawings, :except => [:edit, :update]
  end

  root :to => 'prompts#new'

end

app/models/prompt.rb
class Prompt < ActiveRecord::Base
  include Utils
  attr_accessor :promptData
  attr_accessible :image, :promptData, :drawings_attributes, :colors
  before_validation :save_promptData

  has_many :drawings, :dependent => :destroy, :inverse_of => :prompt

  accepts_nested_attributes_for :drawings, :limit => 1

  mount_uploader :image, PromptUploader

  validates_format_of :colors, :with => /\A\[(\[(\d{1,3},){3}\d{1,3}\],){0,19}\[(\d{1,3},){3}\d{1,3}\]\]\z/


  def save_promptData
    self.image = save_image_data promptData
  end


end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  before_filter :get_user
  # GET /prompts
  # GET /prompts.json
  def index
    #@prompts = Prompt.all
    @prompts = Prompt.page(params[:page]).per(10)

    respond_to do |format|
      format.js
      format.html # index.html.erb
      format.json { render json: @prompts }
    end
  end

  # GET /prompts/1
  # GET /prompts/1.json
  def show
    @prompt = Prompt.find(params[:id])
    @drawings = @prompt.drawings
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prompt }
    end
  end

  # GET /prompts/new
  # GET /prompts/new.json
  def new
    @prompt = Prompt.new
    @prompt.drawings.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prompt }
    end
  end

  # GET /prompts/1/edit
  def edit
    @prompt = Prompt.find(params[:id])
  end

  # POST /prompts
  # POST /prompts.json
  def create
    params[:prompt][:drawings_attributes].values.each do |d|
      d[:user_id] = current_user.id
    end

    @prompt = Prompt.new(params[:prompt])

    respond_to do |format|
      if @prompt.save
        format.html { redirect_to @prompt, notice: 'Prompt was successfully created.' }
        format.json { render json: @prompt, status: :created, location: @prompt }
      else
        format.html { render action: 'new' }
        format.json { render json: @prompt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /prompts/1
  # PUT /prompts/1.json
  def update
    @prompt = Prompt.find(params[:id])

    respond_to do |format|
      if @prompt.update_attributes(params[:prompt])
        format.html { redirect_to @prompt, notice: 'Prompt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @prompt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prompts/1
  # DELETE /prompts/1.json
  def destroy
    @prompt = Prompt.find(params[:id])
    @prompt.destroy

    respond_to do |format|
      format.html { redirect_to prompts_url, notice: 'Prompt was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def get_user
    @user = current_user
  end
end

app/helpers/prompts_helper.rb
module PromptsHelper
end

app/views/prompts/_form.html.haml
= form_for @prompt do |f|
  - if @prompt.errors.any?
    #error_explanation
      %h2= "#{pluralize(@prompt.errors.count, 'error')} prohibited this prompt from being saved:"
      %ul
        - @prompt.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :image
    = f.text_field :image
  .actions
    = f.submit 'Save'

app/views/prompts/_prompt.haml
= content_tag 'li', :class => 'promptItem galleryItem', :data => {drawings: prompt.drawings[0..9],
  has_more: (prompt.drawings.length > 10)} do
  .promptCard.galleryCard.hasSlideIn
    = image_tag prompt.image, :class => 'prompt'
    %ul.slideIns
      %li.slideIn
        -# = link_to "View Drawings", prompt_drawings_path(prompt)
        = link_to image_tag(asset_path('gallery-icons/view.png')), prompt
      %li.slideIn
        -# = link_to "View the Prompt", prompt_path(d.prompt)
        = link_to image_tag(asset_path('gallery-icons/draw.png')), new_prompt_drawing_path(prompt)
      %li.slideIn.openFolder
        = image_tag(asset_path('gallery-icons/tiles.png'))


app/views/prompts/edit.html.haml
%h1 Editing prompt

= render 'form'

= link_to 'Show', @prompt
\|
= link_to 'Back', prompts_path

app/views/prompts/index.html.haml
- content_for :stylesheets do
  = stylesheet_link_tag asset_path('gallery.css')

- content_for :javascripts do
  = javascript_include_tag asset_path('gallery.js')

%ul#prompts.gallery
  = render @prompts

- if link_to_next_page @prompts, ''
  #loadmore
    Load more...

#pages
  = paginate @prompts

app/views/prompts/index.js.erb
var calculateGalleryWidth = function()
{
    return Math.floor($(window).width() / $('.galleryItem').width()) * $('.galleryItem').width();
};

var reactToResize = function()
{
    $('.folder').stop(true, true).remove();
    $('.clicked').removeClass('clicked');
    $('.gallery').width(calculateGalleryWidth());
};

$('.folder').slideUp(reactToResize);


$('.galleryItem').addClass('preexisting');

$('.gallery').append('<%= j render @prompts %>');

<% if link_to_next_page @prompts, '' %>
    $('.pagination').replaceWith('<%= j paginate @prompts %>');
    $('#loadmore').text('Load more...');
<% else %>
    $('#loadmore').fadeOut({conplete: function(){$('#loadmore').remove()}});
    $('.pagination').remove();
<% end %>

bindPromptItems($('.galleryItem').not('.preexisting'));

app/views/prompts/new.html.haml
= render 'draw/canvases'
= render 'draw/promptDrawingsNestedForm'

app/views/prompts/show.html.haml
- content_for :stylesheets do
  = stylesheet_link_tag asset_path('gallery.css')

- content_for :javascripts do
  = javascript_include_tag asset_path('gallery.js')
  = javascript_include_tag asset_path('drawings.js')

- content_for :page_info do
  - if not @prompt.drawings.empty?
    %li
      = link_to 'First drawn by ' + @prompt.drawings.first.user.name, @prompt.drawings.first.user
  %li
    = link_to 'Draw this inkblot', new_prompt_drawing_path(@prompt)
  - if current_user and current_user.is_admin?
    %li{:class => ('destructiveAction adminOption')}
      = link_to 'Delete this inkblot', @prompt, confirm: 'Are you sure? This will also delete every interpretation.',
             method: :delete

#showPrompt
  = image_tag @prompt.image

%ul#drawings.gallery
  = render @drawings