config/routes.rb
Rorschach::Application.routes.draw do


  get 'info', to: 'static#info'
  get 'user/:name', to: 'users#show'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'auth/failure', to: redirect('/')
  match 'drawings', to: 'drawings#all', as: 'drawings'
  match 'kitteh', to: 'kitteh#index', as: 'kitteh'


  resources :users, :only => [:index, :show, :update]

  # resources :prompts, :except => [:edit, :update] do
  resources :inkblots, :except => [:edit, :update], :controller => 'prompts', :as => 'prompts' do
    resources :drawings, :except => [:edit, :update]
  end

  root :to => 'prompts#new'

end

app/models/drawing.rb
class Drawing < ActiveRecord::Base
  include Utils
  attr_accessor :drawingData
  attr_accessible :drawingData, :image, :user_id
  before_validation :save_drawingData

  belongs_to :prompt, :inverse_of => :drawings
  belongs_to :user, :inverse_of => :drawings

  mount_uploader :image, PromptUploader
  validates_presence_of :user
  validates_presence_of :prompt

  def save_drawingData
    self.image = save_image_data drawingData
  end

end

app/controllers/drawings_controller.rb
class DrawingsController < ApplicationController
  before_filter :get_prompt, :get_user

  # GET /drawings
  # GET /drawings.json
  def index
    @drawings = @prompt.drawings
    respond_to do |format|
      format.html { redirect_to @prompt }# index.html.erb
      #format.html
      format.json { render json: @drawings }
    end
  end

  def all
    @drawings = Drawing.page(params[:page]).per(10)
  end

  # GET /drawings/1
  # GET /drawings/1.json
  def show
    @drawing = @prompt.drawings.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @drawing }
    end
  end

  # GET /drawings/new
  # GET /drawings/new.json
  def new
    @drawing = @prompt.drawings.build
    @drawing.user = @user
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @drawing }
    end
  end

  # GET /drawings/1/edit
  def edit
    @drawing = @prompt.drawings.find(params[:id])
  end

  # POST /drawings
  # POST /drawings.json
  def create
    @drawing = @prompt.drawings.build(params[:drawing])
    @drawing.user = @user

    respond_to do |format|
      if @drawing.save!
        #format.html { redirect_to @drawing, notice: 'drawing was successfully created.' }
        format.html { redirect_to @prompt, notice: 'Drawing was successfully created' }
        format.json { render json: @drawing, status: :created, location: @drawing }
      else
        format.html { render action: 'new' }
        format.json { render json: @drawing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /drawings/1
  # PUT /drawings/1.json
  def update
    @drawing = @prompt.find(params[:id])

    respond_to do |format|
      if @drawing.update_attributes(params[:drawing])
        #format.html { redirect_to @drawing, notice: 'drawing was successfully updated.' }
        format.html { redirect_to @prompt, notice: 'Drawing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @drawing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drawings/1
  # DELETE /drawings/1.json
  def destroy
    @drawing = @prompt.drawings.find(params[:id])
    @drawing.destroy unless not current_user or (current_user != @drawing.user and not current_user.is_admin)

    respond_to do |format|
      #format.html { redirect_to drawings_url }
      format.html { redirect_to @prompt, notice: 'Drawing was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def get_prompt
      if params[:prompt_id]
        @prompt = Prompt.find(params[:prompt_id])
      end
    end

    def get_user
      @user = current_user
    end
end

app/helpers/drawings_helper.rb
module DrawingsHelper
end

app/views/drawings/_drawing.haml
%li.drawingItem.galleryItem
  .drawingCard.galleryCard.hasSlideIn
    = image_tag drawing.image, :class => 'drawing'
    = image_tag drawing.prompt.image, :class => 'prompt'
    %ul.slideIns
      %li.slideIn
        = link_to image_tag(asset_path('gallery-icons/view.png')), prompt_drawing_path(drawing.prompt, drawing)
      -#%li.slideIn
      -#  = link_to image_tag(asset_path('gallery-icons/draw.png')), new_prompt_drawing_path(drawing.prompt)
      -#%li.slideIn.toggleInkblot
      -#  = image_tag asset_path('gallery-icons/inkblot.png')
      %li.slideIn
        = link_to (image_tag asset_path('gallery-icons/inkblot.png')), drawing.prompt
      %li.slideIn
        = link_to image_tag(asset_path('gallery-icons/user.png')), drawing.user

app/views/drawings/_form.html.haml
= form_for [@prompt, @drawing] do |f|
  - if @drawing.errors.any?
    #error_explanation
      %h2= "#{pluralize(@drawing.errors.count, 'error')} prohibited this drawing from being saved:"
      %ul
        - @drawing.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/drawings/all.html.haml
- content_for :stylesheets do
  = stylesheet_link_tag asset_path('gallery.css')

%ul#drawings.gallery
  = render @drawings

- if link_to_next_page @drawings, ''
  #loadmore
    Load more...
#pages
  = paginate @drawings

app/views/drawings/all.js.erb
$('.galleryItem').addClass('preexisting');

$('.gallery').append('<%= j render @drawings %>');

<% if link_to_next_page @drawings, '' %>
    $('.pagination').replaceWith('<%= j paginate @drawings %>');
    $('#loadmore').text('Load more...');
<% else %>
    $('#loadmore').fadeOut({conplete: function(){$('#loadmore').remove()}});
    $('.pagination').remove();
<% end %>

bindDrawingItems($('.galleryItem').not('.preexisting'));

app/views/drawings/edit.html.haml
%h1 Editing drawing

= render 'form'

= link_to 'Show', [@prompt, @drawing]
\|
= link_to 'Back', prompt_drawings_path(@prompt)

app/views/drawings/index.html.haml
- content_for :stylesheets do
  = stylesheet_link_tag asset_path('gallery.css')

- content_for :page_info do
  = link_to '<< Back to the prompt', @prompt


%ul#drawings.gallery
  = render @drawings

app/views/drawings/new.html.haml
- content_for :javascripts do
  :javascript
    window.prompt_url = '#{@prompt.image}'
    window.colors = #{@prompt.colors || 'null'};

= render 'draw/canvases'

= form_for [@prompt, @drawing], :html => {:id => 'submitPrompt'} do |f|
  = f.hidden_field :drawingData, :id => 'drawingData'

app/views/drawings/show.html.haml
- content_for :page_info do
  %li
    = link_to 'Drawn by ' + @drawing.user.name, @drawing.user
  - if current_user and ((current_user.id == @drawing.user_id) or current_user.is_admin)
    %li{:class => ('destructiveAction' + (current_user.is_admin ? ' adminOption' : ''))}
      = link_to 'Delete this drawing', [@prompt, @drawing], confirm: 'Are you sure? I think it\'s beautiful',
       method: :delete
  %li
    = link_to 'View the inkblot', @prompt

#drawingWrapper
  = image_tag @drawing.image, id: 'drawing'
  = image_tag @prompt.image, id: 'prompt'