config/routes.rb
Rorschach::Application.routes.draw do


  get 'info', to: 'static#info'
  get 'user/:name', to: 'users#show'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'auth/failure', to: redirect('/')
  match 'drawings', to: 'drawings#all', as: 'drawings'
  match 'kitteh', to: 'kitteh#index', as: 'kitteh'


  resources :users, :only => [:index, :show, :update]

  # resources :prompts, :except => [:edit, :update] do
  resources :inkblots, :except => [:edit, :update], :controller => 'prompts', :as => 'prompts' do
    resources :drawings, :except => [:edit, :update]
  end

  root :to => 'prompts#new'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Rorschach
    = stylesheet_link_tag 'application', :media => 'all', :class => 'cssfx'
    = stylesheet_link_tag params['controller'], :class => 'cssfx'
    = stylesheet_link_tag 'jquery.jscrollpane'

    = yield :stylesheets

    = javascript_include_tag 'application'
    = javascript_include_tag params['controller']

    = yield :javascripts

    :javascript
      window.is_logged_in = #{not current_user.nil?}

    %link{:rel => 'apple-touch-icon-precomposed', :href => image_path('app-icons/Icon.png') }
    %link{:rel => 'apple-touch-icon-precomposed',:sizes => '72x72', :href => image_path('app-icons/Icon-72.png') }
    %link{:rel => 'apple-touch-icon-precomposed',:sizes => '144x144', :href => image_path('app-icons/Icon-72@2x.png') }



    %meta{'name' => 'viewport', :content => 'user-scalable=no,width=600'}/
    = csrf_meta_tags
  %body
    -##notice
    -#  %h3 #{flash[:notice]}
    #header.collapsed
      #headerPull
        = image_tag asset_path('menu.png'), :id => 'toggleMenu'
      #menu
        %ul#pageInfo
          - if (yield :page_info).length != 0
            = yield :page_info
          %li
            = link_to 'View all inkblots', prompts_path()
          %li
            = link_to 'View all drawings', drawings_path()
          -if current_user
            %li
              = link_to 'View Your drawings', current_user
          %li
            = link_to 'Draw a new inkblot', new_prompt_path()
        %ul#sessionInfo
          -if current_user
            %li
              #{link_to 'Sign out', signout_path}
          -else
            %li
              = link_to 'Sign in with Twitter', '/auth/twitter'
          %li
            = link_to 'Info and FAQ', info_path()
    = yield